### ISSUE TITLE
Reason for cancellation missing

### ISSUE THREAD

**Issue by joeri-jansen** [cesniti/erinot_xsd#3]
The EDIFACT version has a field 'reason for cancellation'. In the XSD, this field is not present. Our suggestion is to add this to the XSD, in order to prevent the loss of information when EDIFACT messages are converted to XML.

**Comment by jverstichel** [comment]
Version 1.3 of the xsd has the element 'CancellationInfo' which should fully cover the mentioned EDIFACT field.

Could you please double check that you were looking in the right branch (release/1.3.0) and if so, specify where the current implementation of CancellationInfo is failing to implement the 'reason for cancellation'?

**Comment by joeri-jansen** [comment]
Again, the file in this repository is different than the one we received. You are correct, all required CancellationInfo seems to be present.
