### ISSUE TITLE
v1.3 Old vessel types still present

### ISSUE THREAD

**Issue by joeri-jansen** [cesniti/erinot_xsd#4]
In ERINOT 1.3 the vessel types OFS and ERN are removed. However, they are still present in the XSD. Our suggestion would be to remove them from the v1.3 XSD

**Comment by jverstichel** [comment]
I find no references to OFS and ERN in the xsd version 1.3
Could you please double check that you were looking in the right branch (release/1.3.0) and if so, specify where exactly OFS and ERN numbers are still mentioned?

**Comment by joeri-jansen** [comment]
You are correct. The 1.3-version we received still contained the old references, the one in this repository is correct.
